#!/usr/bin/bash

rm -f yy-all

(
    cat sparql-first.html
    ./processor < content.html
    cat sparql-last.html
##     for X in xx???
##     do
## 	echo
## 	echo "    <section>"
## 	cat $X | sed '1d;$d' | perl -p -e 's/(^ *<h\d>)<a.*>\d+ /$1/'
## 	echo "    </section>"
##     done
) > doc0.html
